################################################################
#
# This is the configurable part of the Makefile.
# It must be named 'Makefile.config'.
#
#
################################################################

################
#
# For each conditional install option, either fill in "yes" or leave 
# blank to indicate no.

# Do you want to use the GL-based renderer?
export RENDER_GL = yes

# Do you want to use the Performer-based renderer?
export RENDER_PF =


# Do you want to use the OpenInventor-based renderer?
export RENDER_IV =


################
#
# Define the OS to compile for and the compiler to use.

OS = Linux

C++ = g++

################
#
# Define the C++ compiler flags

C++FLAGS = -g -Wall
LDFLAGS =  -L/home/roomba/code/msl/pqp-1.3/PQP_v1.3/lib -L/usr/lib 
CPPFLAGS =  -I/home/roomba/code/msl/pqp-1.3/PQP_v1.3/include -I/usr/include/fox-1.6
LDLIBS  = -lPQP 

######### FOX Configuration
#FOXINC = @FOX_INC_F@
#FOXLIB = @FOX_LIB_F@ @PNG_LIB_F@ @JPEG_LIB_F@ -lFOX -ljpeg -lpng
FOXINC = -I/usr/include/fox-1.6
FOXLIB = -lFOX -ljpeg -lpng
FOXFLAGS = -DTIME_WITH_SYS_TIME=1 -DHAVE_UNISTD_H=1 -DHAVE_DIRENT_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_ZLIB_H=1 -DHAVE_JPEGLIB_H=1 -DHAVE_PNG_H=1 -DHAVE_OPENGL -DHAVE_JPEG



#########  PQP Configuration
PQPINC = -I/home/roomba/code/msl/pqp-1.3/PQP_v1.3/include
PQPLIB = -L/home/roomba/code/msl/pqp-1.3/PQP_v1.3/lib -lPQP
PQPFLAGS =
#PQPLIB = -lPQP
#PQPINC = @INCPQP@
#PQPLIB = @LDPQP@ -lPQP
#PQPLIB = -lPQP
#PQPFLAGS =

######### X11 Configuration
XINC=-I
XLIB= -lX11 -lXmu -lXext -lXi -lXcursor

########   GL Configuration
#GLINC = @GL_INC_F@  @GLUT_INC_F@
#GLLIB = @GL_LIB_F@ @GLUT_LIB_F@ -lglut -lGLU -lGL 
GLLIB = -lpthread -lglut -lGLU -lGL -ltiff -lXft -lfontconfig -lalleg
GLFLAGS = 

########   Performer Configuration
#PFINC = @PF_INC_F@
#PFLIB = @PF_LIB_F@ -lpfdu -lpfui -lpfuiD -lpfutil -lpf -ldl
PFLIB = -lpfdu -lpfui -lpfuiD -lpfutil -lpf -ldl
PFFLAGS = -g

########   OpenInventor Configuration
#IVINC = @IV_INC_F@
#IVLIB = @IV_LIB_F@  -lInventor -lInventorXt -lXm -lGLU -lGL -ldl -lXaw
IVLIB = -lInventor -lInventorXt -lXm -lGLU -lGL -ldl -lXaw
IVFLAGS = -DPOSIX_SOURCE -D_XOPEN_SOURCE


######### Others
OTHERINC = -I../include
OTHERLIB = -L../lib -lm 
